In [12]:
import numpy as np
import scipy
import math
from scipy.optimize import minimize

In [7]:
n = 4
lamb = 1/(32*math.sqrt(n))

In [11]:
A = np.random.randint(2, size=(n,n))
print(A)

[[0 0 1 1]
 [1 0 0 1]
 [1 1 0 0]
 [0 1 1 0]]


In [13]:
def nuclear_norm(A):
    s = np.linalg.svd(A, compute_uv=False)
    nuclear_norm = np.sum(s)
    return nuclear_norm

In [14]:
def L1norm(A):
    s = np.sum(np.abs(A))
    return s

In [15]:
def objective(B, K):
    return lamb*L1norm(B) + nuclear_norm(K)

In [16]:
def constraint(A, B, K):
    diff = B + K -A - np.identity(n)
    return L1norm(diff)

In [ ]:
def optCluster(A):
    while(1):
        bounds = 

In [ ]:
# Define the initial guess
x0 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Define the constant value
C = 10

# Define the bounds on x
bounds = ((0, 10), ) * 8

# Define the constraint dictionary
con = {'type': 'eq', 'fun': constraint, 'args': (C, )}

# Use the minimize function to find the minimum
res = minimize(objective, x0, method='SLSQP', bounds=bounds, constraints=con)

# Print the results
print("Minimum value:", res.fun)
print("Minimizing x values:", res.x)
