In [2]:
import numpy as np
import scipy

In [3]:
import numpy as np

# Example binary matrix
A = np.array([[0, 1, 0, 1],
              [1, 0, 1, 0],
              [0, 1, 0, 1],
              [1, 0, 1, 0]])

# Initialize the two binary matrices
B = np.zeros_like(A)
C = np.zeros_like(A)

# Iterate over the rows and columns of A
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        # If A[i,j] is 1, try adding it to B first
        if A[i,j] == 1 and np.sum(B[:,j]) < np.sum(A[:,j])/2:
            B[i,j] = 1
        # If adding to B would make the column sums exceed half of the total,
        # add it to C instead
        elif A[i,j] == 1:
            C[i,j] = 1

# Verify that A = B + C
# assert np.all(A == B + C)

print(B)
print(C)



[[0 1 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 1]
 [1 0 1 0]]


In [4]:
import numpy as np

# Example binary matrix
A = np.array([[0, 1, 0, 1],
              [1, 0, 1, 0],
              [0, 1, 0, 1],
              [1, 0, 1, 0]])

# Compute the column sums of A
col_sums = np.sum(A, axis=0)

# Initialize the two binary matrices
B = np.zeros_like(A)
C = np.zeros_like(A)

# Iterate over the columns of A
for j in range(A.shape[1]):
    # Add the first ceil(col_sum/2) entries to B
    col_sum = col_sums[j]
    half_sum = int(np.ceil(col_sum / 2))
    B[:half_sum, j] = A[:half_sum, j]
    # Add the remaining entries to C
    C[half_sum:col_sum, j] = A[half_sum:col_sum, j]

# Verify that A = B + C
# assert np.all(A == B + C)
print(B)
print(C)

[[0 1 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 0]]


Generating sparse  matrices
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.random.html

In [5]:
from scipy.sparse import random
from scipy import stats
from numpy.random import default_rng

In [15]:
A = random(4, 4, 0.1)
print(A.shape)
print(A.A)

(4, 4)
[[0.         0.47879003 0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.96766427 0.         0.        ]
 [0.         0.         0.         0.        ]]


Here, density = m^2/n^2